services:
  - type: web
    name: nutriscan-food-labels-insights
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn ocr_project_pr1.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_OAUTH2_KEY
        value: 990390516510-i43uhpe18le8vcdgeu1oino13nqfs821.apps.googleusercontent.com
      - key: GOOGLE_OAUTH2_SECRET
        value: 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
      - key: DATABASE_URL
        fromDatabase:
          name: nutriscan-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: nutriscan-db
    databaseName: nutriscan
    user: nutriscan_user
    plan: free
